### PR TITLE
Available Cards added to README.md

### LINKED ISSUE #12: Add Flat new style Badges in README.md

### PR DESCRIPTION
**Pull request by kosijer**
Closes #12 

image

### CODE REVIEW

**Comment by aashutoshrathi** [comment]
This PR doesn't fixes #12

**Comment by kosijer** [comment]
Can you give me then more details what should be done then? Thanks

**Comment by aashutoshrathi** [comment]
I meant to add flat style shield badges, what you did can be done in a separate PR for another issue which you can create 😄

**Comment by kosijer** [comment]
OK, I just did it :)
Can you just add Hacktober label on it, reopen this PR and then I'll connect it to the issue? :)

How many badges you need for this one and what is their purpose?

**Pull request closed without merging**
